### PR TITLE
Beautification - About in Kor.

### PR DESCRIPTION
**Pull request by MoonkiHong**
- Style amendment w.r.t. the markdown syntax.

### CODE REVIEW

**Review by limisaac — APPROVED** [review]
Updates on styling looks good.

**Review by fesfojas — APPROVED** [review]
No additional comments on changes to styling

**Comment by MoonkiHong** [comment]
> Hi Moonki! Would just like to inform you that there are other .md pages for About namely: Motivation, Charter, Members, and Logo.

Right. Charter will be documented separately. And I need more consideration in assigning the right section within the current About page in terms of Motivation, Members, and Logo. Stay tuned.

**Comment by fesfojas** [comment]
> > Hi Moonki! Would just like to inform you that there are other .md pages for About namely: Motivation, Charter, Members, and Logo.
> 
> Right. Charter will be documented separately. And I need more consideration in assigning the right section within the current About page in terms of Motivation, Members, and Logo. Stay tuned.

Copy Moonki. Thank you :)

**Pull request merged**
